#!/usr/bin/env python
import os
print ("CREDITOS AL DEVOLEPER")
print ("CREADOR: Real Strategy")
print ("DATE: 12/07/2018")
print ("TELEGRAM: https://t.me/RealHackRWAM")
print ("YOUTUBE: https://www.youtube.com/TodoReal")
print ("MENSAJE: Nunca dejes de aprender")
print ("")

raw_input("Presiona enter para continuar")
os.system("python2 cc-genpro2.0.py")
